services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s    

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5555:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  inventory-api:
    image: inventory-api
    build:
      context: ./InventoryAPI
      dockerfile: Dockerfile
    ports:
      - "5041:5041"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Username=myuser;Password=mypassword;Database=mydb
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres:
  pgadmin: